CI updates and stuff (#374)
* [meta] add a prettier workflow for pushes to main

* [fix] remove running fmt

It can't write to files in this context, so it would just pop a spurious warning (not even an error)

* [fix] bump checkout action version and remove headref

* [meta] add action and yaml linting

* [dep] update setup-node

* [fix] yamllint warnings

* Add a configuration file for yamllint

* Update ci-main.yml

fallback for `yarn audit` failing

* Update CODEOWNERS

entries for newly added or modified files

---------

Co-authored-by: Eric Gallager <egall@gwmail.gwu.edu>

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -16,7 +16,7 @@ jobs:
     continue-on-error: true
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
+      - uses: actions/setup-node@v4.1.0
         with:
           node-version: '18'
       - name: Package install
@@ -40,13 +40,12 @@ jobs:
         run: |
           zip "blue-blocker-source-$(make version).zip" -r ./* -x ".git/*" \
            "build/*" "node_modules/*" ".vscode/*" ".editorconfig"
-      - name: Package formatting
-        run: npm run fmt
+
   test-with-yarn:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
+      - uses: actions/setup-node@v4.1.0
         with:
           node-version: '18'
       - name: Package install
@@ -58,4 +57,17 @@ jobs:
       - name: Package test
         run: yarn check || yarn run build || vite build || make
       - name: Package audit
-        run: yarn audit || yarn run fmt
+        run: yarn audit || echo "audit failed, but whatever, nothing matters"
+
+  linting:
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    steps:
+      - uses: actions/checkout@v4
+      - name: actionlint
+        uses: devops-actions/actionlint@v0.1.3
+      - name: yamllint
+        uses: reviewdog/action-yamllint@v1
+        with:
+          reporter: github-pr-review
+          yamllint_flags: '.github/'
